//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppAssetEntities : DbContext
    {
        public AppAssetEntities()
            : base("name=AppAssetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppADGroup> AppADGroups { get; set; }
        public virtual DbSet<AppAscHardware> AppAscHardwares { get; set; }
        public virtual DbSet<AppAscRprt> AppAscRprts { get; set; }
        public virtual DbSet<AppAscSoftware> AppAscSoftwares { get; set; }
        public virtual DbSet<AppContract> AppContracts { get; set; }
        public virtual DbSet<AppExpired> AppExpireds { get; set; }
        public virtual DbSet<ApplicationVersion> ApplicationVersions { get; set; }
        public virtual DbSet<AppMain> AppMains { get; set; }
        public virtual DbSet<AppServerDB> AppServerDBs { get; set; }
        public virtual DbSet<AppSupportInfo> AppSupportInfoes { get; set; }
        public virtual DbSet<AppVendor> AppVendors { get; set; }
        public virtual DbSet<AppVendorContact> AppVendorContacts { get; set; }
        public virtual DbSet<AppVendorSupport> AppVendorSupports { get; set; }
    }
}
