//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppADGroup
    {
        public int AppADID { get; set; }
        public string ADName { get; set; }
        public string ADDescription { get; set; }
        public string ADStatus { get; set; }
        public string ADComments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int AppIDFK { get; set; }
    
        public virtual AppMain AppMain { get; set; }
    }
}
