//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAscRprt
    {
        public int AppServerID { get; set; }
        public int AppIDFK { get; set; }
        public string AppAscRprtName { get; set; }
        public string AppAscRprtServer { get; set; }
        public string AppAscRprtPATH { get; set; }
        public string AppAscRprtUA { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ExpiryFlag { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AppMain AppMain { get; set; }
    }
}
