//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppExpired
    {
        public int ExpireID { get; set; }
        public string Expired { get; set; }
        public int AppIDFK { get; set; }
    
        public virtual AppMain AppMain { get; set; }
    }
}
