//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppServerDB
    {
        public int AppServerID { get; set; }
        public int VersionIDFK { get; set; }
        public string AppServerName { get; set; }
        public string AppServerType { get; set; }
        public string AppServerOS { get; set; }
        public string AppServerURL { get; set; }
        public string AppDBType { get; set; }
        public string AppDBName { get; set; }
        public string AppServerIE { get; set; }
    
        public virtual ApplicationVersion ApplicationVersion { get; set; }
    }
}
