//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSupportInfo
    {
        public int AppSupportID { get; set; }
        public int AppIDFK { get; set; }
        public string AppSupportITOwner { get; set; }
        public string AppSupportAdmin { get; set; }
        public string AppSupportBOG { get; set; }
        public string AppSupportPMR { get; set; }
        public string AppHours { get; set; }
        public string AppMaintenance { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AppMain AppMain { get; set; }
    }
}
