//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppServerDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppServerDB()
        {
            this.ApplicationVersions = new HashSet<ApplicationVersion>();
        }
    
        public int AppServerID { get; set; }
        public int AppIDFK { get; set; }
        public string AppServerName { get; set; }
        public string AppServerType { get; set; }
        public string AppServerOS { get; set; }
        public string AppServerURL { get; set; }
        public string AppDBType { get; set; }
        public string AppDBName { get; set; }
        public string AppServerIE { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationVersion> ApplicationVersions { get; set; }
        public virtual AppMain AppMain { get; set; }
    }
}
