//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVendorSupport
    {
        public int VenSupportID { get; set; }
        public string VenSupportHours { get; set; }
        public string VenSupportNum { get; set; }
        public string VenSupportEmail { get; set; }
        public string VenSupportComments { get; set; }
        public int VenIDFK { get; set; }
    
        public virtual AppVendor AppVendor { get; set; }
    }
}
